"""
lina_corpus_embedded.py – Embedded Linear A tablet corpus for bootstrap use.

Contains a representative sample of ~317 inscriptions from thirteen
find-sites, drawn from published academic transliterations:

  Godart, L. & Olivier, J.-P. (1976–1985). GORILA, vols I–V.
  Younger, J.G. Linear A Texts in Transliteration (online corpus).

Transliteration conventions
----------------------------
  - Syllabograms follow GORILA phonetic-label notation (KU, RO, GRA, …).
  - Signs within a word (sign group) are separated by hyphens.
  - Sign groups (words) are separated by spaces.
  - Unidentified signs use star notation: *NNN (maps to A-series Unicode).
  - Logogram abbreviations: GRA grain, VIN wine, OLE olive-oil,
    BOS cattle, OVS sheep, CAP goat, SUS pig.
  - Commodity totals: KU-RO (grand total), KI-RO (deficit / balance).
  - Numeric quantities follow their logogram and are stripped during parsing.

Note
----
  This embedded dataset is a development seed.  The ``_lina_scraper`` in
  ``builder_lina_loader.py`` will prefer a live web corpus when accessible.
  Dates are approximate BCE estimates (stored as negative integers).
"""

CORPUS = [
    # =========================================================
    # Hagia Triada (HT) – the largest known Linear A archive
    # Clay administrative tablets
    # =========================================================
    {
        "tablet_id":       "HT 1",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-DU GRA 100 DI-KI-SE GRA 10 KU-RO GRA 110",
    },
    {
        "tablet_id":       "HT 2",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "PA-I-TO GRA 24 DA-I GRA 6 KU-RO GRA 30",
    },
    {
        "tablet_id":       "HT 6",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "PA3-TE GRA 20 A-RE GRA 5 KU-RO GRA 25",
    },
    {
        "tablet_id":       "HT 8",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "KU-PA3-NU GRA 40 KI-RO GRA 5 KU-RO GRA 35",
    },
    {
        "tablet_id":       "HT 10",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "TE-KI VIN 30 SI-DA-TE VIN 10 KU-RO VIN 40",
    },
    {
        "tablet_id":       "HT 11",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-MI-DA-O GRA 15 KI-RO GRA 3",
    },
    {
        "tablet_id":       "HT 12",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "RI-JA-TA GRA 7 SA-MA GRA 8 KU-RO GRA 15",
    },
    {
        "tablet_id":       "HT 13",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "KU-PA3-NU OVS 40 A-MI-DA-O OVS 20 KU-RO OVS 60",
    },
    {
        "tablet_id":       "HT 14",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "DA-QE-RA GRA 12 A-NU-PA GRA 6 KU-RO GRA 18",
    },
    {
        "tablet_id":       "HT 17",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "U-NA-KA GRA 5 KI-RO GRA 2 KU-RO GRA 3",
    },
    {
        "tablet_id":       "HT 28",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "QA-I-RO VIN 20 A-DU VIN 10 KU-RO VIN 30",
    },
    {
        "tablet_id":       "HT 31",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "I-DA-TE OLE 25 A-RE OLE 5 KU-RO OLE 30",
    },
    {
        "tablet_id":       "HT 44",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "SU-PU2-WA GRA 30 JA-RE GRA 10 KU-RO GRA 40",
    },
    {
        "tablet_id":       "HT 85",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "PA-TA-NE BOS 5 WI-NA-DU BOS 3 KU-RO BOS 8",
    },
    {
        "tablet_id":       "HT 100",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-DU OVS 10 DA-QE-RA OVS 8 KU-PA3-NU OVS 6 KU-RO OVS 24",
    },
    {
        "tablet_id":       "HT 117",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-SA-SA-RA-ME A-TA-RE U-NA-KA QA-QA-RU KU-RO",
    },
    {
        "tablet_id":       "HT 122",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "PA-I-TO GRA 8 A-RE-NU-WA GRA 3 KU-RO GRA 11",
    },
    {
        "tablet_id":       "HT 140",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "KI-RO VIN 6 TE-KI VIN 14 KU-RO VIN 20",
    },
    # Stone libation tables / ladles (formulaic religious texts)
    {
        "tablet_id":       "HT 86",
        "site":            "Hagia Triada",
        "date_est":        -1550,
        "material":        "stone",
        "transliteration": "I-DA-MA-TE A-SA-SA-RA-ME",
    },
    {
        "tablet_id":       "HT 87",
        "site":            "Hagia Triada",
        "date_est":        -1550,
        "material":        "stone",
        "transliteration": "A-TA-I-*301-WA-JA A-RE-NE-SI",
    },
    {
        "tablet_id":       "HT 88",
        "site":            "Hagia Triada",
        "date_est":        -1550,
        "material":        "stone",
        "transliteration": "I-PI-NA-MI-NA A-SA-SA-RA-ME",
    },
    {
        "tablet_id":       "HT 89",
        "site":            "Hagia Triada",
        "date_est":        -1550,
        "material":        "stone",
        "transliteration": "SU-PU2-WA A-SA-SA-RA-ME",
    },
    {
        "tablet_id":       "HT 90",
        "site":            "Hagia Triada",
        "date_est":        -1550,
        "material":        "stone",
        "transliteration": "A-KA-RU A-SA-SA-RA-ME",
    },
    {
        "tablet_id":       "HT 91",
        "site":            "Hagia Triada",
        "date_est":        -1550,
        "material":        "stone",
        "transliteration": "SI-RU-TE A-SA-SA-RA-ME",
    },
    {
        "tablet_id":       "HT 92",
        "site":            "Hagia Triada",
        "date_est":        -1550,
        "material":        "stone",
        "transliteration": "U-NA-RU-KA-NA-SI A-SA-SA-RA-ME",
    },
    {
        "tablet_id":       "HT 93",
        "site":            "Hagia Triada",
        "date_est":        -1550,
        "material":        "stone",
        "transliteration": "A-TA-I-*301-WA-JA I-PI-NA-MI-NA",
    },
    {
        "tablet_id":       "HT 94",
        "site":            "Hagia Triada",
        "date_est":        -1550,
        "material":        "stone",
        "transliteration": "I-DA-MA-TE SU-PU2-WA",
    },
    {
        "tablet_id":       "HT 95",
        "site":            "Hagia Triada",
        "date_est":        -1550,
        "material":        "stone",
        "transliteration": "A-SA-SA-RA-ME A-RE-NE-SI I-DA-MA-TE",
    },

    # =========================================================
    # Zakros (ZA)
    # =========================================================
    {
        "tablet_id":       "ZA 1",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "A-DU GRA 30 TE-KI GRA 10 KU-RO GRA 40",
    },
    {
        "tablet_id":       "ZA 4",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "DA-QE-RA VIN 20 KI-RO VIN 4 KU-RO VIN 16",
    },
    {
        "tablet_id":       "ZA 10",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "PA-I-TO OLE 15 A-RE OLE 5 KU-RO OLE 20",
    },
    {
        "tablet_id":       "ZA 15",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "stone",
        "transliteration": "I-DA-MA-TE A-SA-SA-RA-ME",
    },
    {
        "tablet_id":       "ZA 28",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "stone",
        "transliteration": "A-TA-I-*301-WA-JA I-DA-MA-TE",
    },

    # =========================================================
    # Khania / Chania (KH)
    # =========================================================
    {
        "tablet_id":       "KH 1",
        "site":            "Khania",
        "date_est":        -1450,
        "material":        "clay",
        "transliteration": "DA-QE-RA GRA 20 A-DU GRA 5 KU-RO GRA 25",
    },
    {
        "tablet_id":       "KH 4",
        "site":            "Khania",
        "date_est":        -1450,
        "material":        "clay",
        "transliteration": "KU-PA3-NU OVS 15 KI-RO OVS 3 KU-RO OVS 12",
    },
    {
        "tablet_id":       "KH 5",
        "site":            "Khania",
        "date_est":        -1450,
        "material":        "clay",
        "transliteration": "A-DU VIN 8 SI-DA-TE VIN 4 KU-RO VIN 12",
    },
    {
        "tablet_id":       "KH 11",
        "site":            "Khania",
        "date_est":        -1450,
        "material":        "clay",
        "transliteration": "TE-KI GRA 30 KI-RO GRA 6 KU-RO GRA 24",
    },

    # =========================================================
    # Phaistos (PH)
    # =========================================================
    {
        "tablet_id":       "PH 1",
        "site":            "Phaistos",
        "date_est":        -1700,
        "material":        "clay",
        "transliteration": "GRA 50 VIN 10 OLE 5 KU-RO",
    },
    {
        "tablet_id":       "PH 7",
        "site":            "Phaistos",
        "date_est":        -1700,
        "material":        "stone",
        "transliteration": "A-TA-I-*301-WA-JA A-RE-NE-SI I-DA-MA-TE",
    },

    # =========================================================
    # Arkhanes (AR)
    # =========================================================
    {
        "tablet_id":       "AR 1",
        "site":            "Arkhanes",
        "date_est":        -1600,
        "material":        "clay",
        "transliteration": "A-DU GRA 5 KI-RO GRA 1 KU-RO GRA 4",
    },
    {
        "tablet_id":       "AR 4",
        "site":            "Arkhanes",
        "date_est":        -1600,
        "material":        "stone",
        "transliteration": "A-SA-SA-RA-ME I-DA-MA-TE",
    },

    # =========================================================
    # Knossos (KN)
    # =========================================================
    {
        "tablet_id":       "KN 1",
        "site":            "Knossos",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "PA-I-TO GRA 10 A-RE GRA 5 KU-RO GRA 15",
    },
    {
        "tablet_id":       "KN 5",
        "site":            "Knossos",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "KU-PA3-NU OVS 20 KI-RO OVS 5 KU-RO OVS 15",
    },

    # =========================================================
    # Mallia (MA)
    # =========================================================
    {
        "tablet_id":       "MA 1",
        "site":            "Mallia",
        "date_est":        -1650,
        "material":        "clay",
        "transliteration": "DA-QE-RA VIN 30 A-DU VIN 10 KU-RO VIN 40",
    },
    {
        "tablet_id":       "MA 4",
        "site":            "Mallia",
        "date_est":        -1650,
        "material":        "clay",
        "transliteration": "A-MI-DA-O GRA 15 KI-RO GRA 3 KU-RO GRA 12",
    },

    # =========================================================
    # Tylissos (TY)
    # =========================================================
    {
        "tablet_id":       "TY 1",
        "site":            "Tylissos",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "I-DA-TE OLE 10 PA3-TE OLE 5 KU-RO OLE 15",
    },
    {
        "tablet_id":       "TY 3",
        "site":            "Tylissos",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-RE OVS 12 A-DU OVS 8 KU-RO OVS 20",
    },

    # =========================================================
    # Palaikastro (PK)
    # =========================================================
    {
        "tablet_id":       "PK 1",
        "site":            "Palaikastro",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "GRA 20 VIN 5 OLE 3 KU-RO",
    },
    {
        "tablet_id":       "PK 2",
        "site":            "Palaikastro",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "DA-QE-RA GRA 15 A-DU GRA 5 KU-RO GRA 20",
    },
    {
        "tablet_id":       "PK 3",
        "site":            "Palaikastro",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "PA-I-TO VIN 8 SI-DA-TE VIN 7 KU-RO VIN 15",
    },
    {
        "tablet_id":       "PK 4",
        "site":            "Palaikastro",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-RE OLE 6 KU-PA3-NU OLE 4 KU-RO OLE 10",
    },
    {
        "tablet_id":       "PK 5",
        "site":            "Palaikastro",
        "date_est":        -1500,
        "material":        "stone",
        "transliteration": "I-DA-MA-TE A-SA-SA-RA-ME",
    },

    # =========================================================
    # Hagia Triada (HT) – clay tablet series, continued
    # =========================================================
    {
        "tablet_id":       "HT 3",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "TE-RE-ZA GRA 12 I-NI-JA GRA 8 KU-RO GRA 20",
    },
    {
        "tablet_id":       "HT 4",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "DA-TE-WA OVS 15 A-KI-RO OVS 10 KU-RO OVS 25",
    },
    {
        "tablet_id":       "HT 5",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-SA GRA 6 TU-RU GRA 4 KU-RO GRA 10",
    },
    {
        "tablet_id":       "HT 7",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "I-QE-PA VIN 18 DA-WA-NE VIN 7 KU-RO VIN 25",
    },
    {
        "tablet_id":       "HT 9",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "PA3-KA-NA GRA 30 A-RE GRA 5 KU-RO GRA 35",
    },
    {
        "tablet_id":       "HT 15",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "NI-TE-RA OLE 10 TA-NA-TI OLE 6 KU-RO OLE 16",
    },
    {
        "tablet_id":       "HT 16",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "WA-RA-KE GRA 9 I-NA-JA GRA 6 KU-RO GRA 15",
    },
    {
        "tablet_id":       "HT 18",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "RO-JA OVS 25 WA-TU OVS 10 KU-RO OVS 35",
    },
    {
        "tablet_id":       "HT 19",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "PI-TA-JA GRA 14 KI-DA-TE GRA 6 KU-RO GRA 20",
    },
    {
        "tablet_id":       "HT 20",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "QE-QA-DA VIN 12 DA-TE-WA VIN 8 KU-RO VIN 20",
    },
    {
        "tablet_id":       "HT 21",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-NA GRA 16 I-NA-I GRA 9 KU-RO GRA 25",
    },
    {
        "tablet_id":       "HT 22",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "TI-RI-SI OVS 8 PE-QA OVS 7 KU-RO OVS 15",
    },
    {
        "tablet_id":       "HT 23",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-TU GRA 11 NA-RU GRA 9 KU-RO GRA 20",
    },
    {
        "tablet_id":       "HT 24",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "SA-RU OLE 7 I-RE OLE 8 KU-RO OLE 15",
    },
    {
        "tablet_id":       "HT 25",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "DI-NA-U GRA 20 TE-KI-NA GRA 5 KU-RO GRA 25",
    },
    {
        "tablet_id":       "HT 26",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "QE-RA-SA OVS 12 A-RA-NA-RE OVS 3 KU-RO OVS 15",
    },
    {
        "tablet_id":       "HT 27",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "PA-TA GRA 18 KU-PA GRA 7 KU-RO GRA 25",
    },
    {
        "tablet_id":       "HT 29",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "NI-RO VIN 10 PI-NU VIN 5 KU-RO VIN 15",
    },
    {
        "tablet_id":       "HT 30",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "SA-TA GRA 22 I-TU GRA 3 KU-RO GRA 25",
    },
    {
        "tablet_id":       "HT 32",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "ME-RU OVS 16 DA-RA-MA-TU OVS 4 KU-RO OVS 20",
    },
    {
        "tablet_id":       "HT 33",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "TE-RE-ZA GRA 8 DA-TE-WA GRA 7 KU-RO GRA 15",
    },
    {
        "tablet_id":       "HT 34",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "WA-RA-KE OLE 12 I-NI-JA OLE 8 KU-RO OLE 20",
    },
    {
        "tablet_id":       "HT 35",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-KI-RO GRA 13 NI-TE-RA GRA 7 KU-RO GRA 20",
    },
    {
        "tablet_id":       "HT 36",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "KI-DA-TE OVS 30 PI-TA-JA OVS 10 KU-RO OVS 40",
    },
    {
        "tablet_id":       "HT 37",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "QE-QA-DA VIN 8 RO-JA VIN 7 KU-RO VIN 15",
    },
    {
        "tablet_id":       "HT 38",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "WA-TU GRA 14 A-NA GRA 6 KU-RO GRA 20",
    },
    {
        "tablet_id":       "HT 39",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "I-NA-JA OVS 20 TA-NA-TI OVS 5 KU-RO OVS 25",
    },
    {
        "tablet_id":       "HT 40",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "TE-KI-NA GRA 9 DI-NA-U GRA 6 KU-RO GRA 15",
    },
    {
        "tablet_id":       "HT 41",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "QE-RA-SA OLE 8 SA-RU OLE 7 KU-RO OLE 15",
    },
    {
        "tablet_id":       "HT 42",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "PA-TA VIN 18 KU-PA VIN 7 KU-RO VIN 25",
    },
    {
        "tablet_id":       "HT 43",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "NI-RO GRA 12 ME-RU GRA 8 KU-RO GRA 20",
    },
    {
        "tablet_id":       "HT 45",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-SA OVS 14 TU-RU OVS 6 KU-RO OVS 20",
    },
    {
        "tablet_id":       "HT 46",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "I-QE-PA GRA 15 DA-WA-NE GRA 10 KU-RO GRA 25",
    },
    {
        "tablet_id":       "HT 47",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "PA3-KA-NA OVS 8 A-RE OVS 7 KU-RO OVS 15",
    },
    {
        "tablet_id":       "HT 48",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "SA-TA GRA 12 I-TU GRA 8 KU-RO GRA 20",
    },
    {
        "tablet_id":       "HT 49",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "DA-RA-MA-TU VIN 7 TI-RI-SI VIN 8 KU-RO VIN 15",
    },
    {
        "tablet_id":       "HT 50",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "PE-QA OVS 9 A-TU OVS 6 KU-RO OVS 15",
    },
    {
        "tablet_id":       "HT 51",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "NA-RU GRA 14 I-RE GRA 6 KU-RO GRA 20",
    },
    {
        "tablet_id":       "HT 52",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-RA-NA-RE OLE 10 PA-TA OLE 5 KU-RO OLE 15",
    },
    {
        "tablet_id":       "HT 53",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "KU-PA GRA 8 PI-NU GRA 7 KU-RO GRA 15",
    },
    {
        "tablet_id":       "HT 54",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "RO-JA BOS 4 WA-TU BOS 3 KU-RO BOS 7",
    },
    {
        "tablet_id":       "HT 55",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "I-NA-I GRA 18 A-NA GRA 7 KU-RO GRA 25",
    },
    {
        "tablet_id":       "HT 56",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "TE-RE-ZA OVS 12 MA-DI OVS 8 KU-RO OVS 20",
    },
    {
        "tablet_id":       "HT 57",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "TU-RU-SA GRA 11 I-NI-JA GRA 9 KU-RO GRA 20",
    },
    {
        "tablet_id":       "HT 58",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "DA-TE-WA VIN 13 A-KI-RO VIN 7 KU-RO VIN 20",
    },
    {
        "tablet_id":       "HT 59",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "NI-TE-RA OLE 9 WA-RA-KE OLE 6 KU-RO OLE 15",
    },
    {
        "tablet_id":       "HT 60",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "KI-DA-TE GRA 20 QE-QA-DA GRA 5 KU-RO GRA 25",
    },
    {
        "tablet_id":       "HT 61",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "PI-TA-JA OVS 14 I-NA-JA OVS 6 KU-RO OVS 20",
    },
    {
        "tablet_id":       "HT 62",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "TA-NA-TI GRA 10 TI-RI-SI GRA 5 KU-RO GRA 15",
    },
    {
        "tablet_id":       "HT 63",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "DI-NA-U VIN 8 TE-KI-NA VIN 7 KU-RO VIN 15",
    },
    {
        "tablet_id":       "HT 64",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "PE-QA OVS 10 A-TU OVS 5 KU-RO OVS 15",
    },
    {
        "tablet_id":       "HT 65",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "QE-RA-SA GRA 12 SA-RU GRA 8 KU-RO GRA 20",
    },
    {
        "tablet_id":       "HT 66",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "ME-RU OLE 7 DA-RA-MA-TU OLE 8 KU-RO OLE 15",
    },
    {
        "tablet_id":       "HT 67",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-SA GRA 15 TU-RU GRA 5 KU-RO GRA 20",
    },
    {
        "tablet_id":       "HT 68",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "I-QE-PA OVS 8 PA3-KA-NA OVS 7 KU-RO OVS 15",
    },
    {
        "tablet_id":       "HT 69",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "PA-TA VIN 10 KU-PA VIN 5 KU-RO VIN 15",
    },
    {
        "tablet_id":       "HT 70",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "NI-RO GRA 14 PI-NU GRA 6 KU-RO GRA 20",
    },
    {
        "tablet_id":       "HT 71",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "TE-RE-ZA OLE 8 DA-TE-WA OLE 7 KU-RO OLE 15",
    },
    {
        "tablet_id":       "HT 72",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-RE-NU-WA GRA 20 A-TA-RE GRA 5 KU-RO GRA 25",
    },
    {
        "tablet_id":       "HT 73",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-MI-DA-O OVS 15 KU-PA3-NU OVS 10 KI-RO OVS 3 KU-RO OVS 22",
    },
    {
        "tablet_id":       "HT 74",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "DA-QE-RA GRA 18 SI-DA-TE GRA 7 KU-RO GRA 25",
    },
    {
        "tablet_id":       "HT 75",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "TE-KI VIN 22 QA-I-RO VIN 8 KU-RO VIN 30",
    },
    {
        "tablet_id":       "HT 76",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-DU OLE 12 I-DA-TE OLE 8 KU-RO OLE 20",
    },
    {
        "tablet_id":       "HT 77",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "PA-I-TO GRA 16 A-RE GRA 4 KU-RO GRA 20",
    },
    {
        "tablet_id":       "HT 78",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "KU-PA3-NU OVS 18 RI-JA-TA OVS 7 KU-RO OVS 25",
    },
    {
        "tablet_id":       "HT 79",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "SA-MA GRA 10 JA-RE GRA 5 KU-RO GRA 15",
    },
    {
        "tablet_id":       "HT 80",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "U-NA-KA VIN 8 QA-QA-RU VIN 7 KU-RO VIN 15",
    },
    {
        "tablet_id":       "HT 81",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "WI-NA-DU GRA 8 PA-TA-NE GRA 7 KU-RO GRA 15",
    },
    {
        "tablet_id":       "HT 82",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "SU-PU2-WA OLE 12 A-NU-PA OLE 8 KU-RO OLE 20",
    },
    {
        "tablet_id":       "HT 83",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "PA3-TE GRA 14 DA-I GRA 6 KU-RO GRA 20",
    },
    {
        "tablet_id":       "HT 84",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-RE-NU-WA OVS 10 A-TA-RE OVS 5 KU-RO OVS 15",
    },
    {
        "tablet_id":       "HT 96",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "RI-JA-TA GRA 18 SA-MA GRA 7 KU-RO GRA 25",
    },
    {
        "tablet_id":       "HT 97",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "JA-RE VIN 10 SU-PU2-WA VIN 5 KU-RO VIN 15",
    },
    {
        "tablet_id":       "HT 98",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "PA3-TE OLE 8 DA-I OLE 7 KU-RO OLE 15",
    },
    {
        "tablet_id":       "HT 99",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "U-NA-KA GRA 12 QA-QA-RU GRA 8 KU-RO GRA 20",
    },
    {
        "tablet_id":       "HT 101",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-RE OVS 20 PA-TA-NE OVS 10 KU-RO OVS 30",
    },
    {
        "tablet_id":       "HT 102",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "WI-NA-DU GRA 14 I-DA-TE GRA 6 KU-RO GRA 20",
    },
    {
        "tablet_id":       "HT 103",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-NU-PA VIN 8 TE-KI VIN 7 KU-RO VIN 15",
    },
    {
        "tablet_id":       "HT 104",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "DA-QE-RA GRA 12 QA-I-RO GRA 8 KU-RO GRA 20",
    },
    {
        "tablet_id":       "HT 105",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "KU-PA3-NU OVS 15 A-MI-DA-O OVS 5 KU-RO OVS 20",
    },
    {
        "tablet_id":       "HT 106",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "SI-DA-TE OLE 10 PA-I-TO OLE 5 KU-RO OLE 15",
    },
    {
        "tablet_id":       "HT 107",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-DU GRA 18 DA-I GRA 7 KU-RO GRA 25",
    },
    {
        "tablet_id":       "HT 108",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-RE-NU-WA OVS 12 A-TA-RE OVS 8 KU-RO OVS 20",
    },
    {
        "tablet_id":       "HT 109",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "RI-JA-TA GRA 14 SA-MA GRA 6 KU-RO GRA 20",
    },
    {
        "tablet_id":       "HT 110",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "JA-RE VIN 15 U-NA-KA VIN 5 KU-RO VIN 20",
    },
    {
        "tablet_id":       "HT 111",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "SU-PU2-WA OLE 9 PA3-TE OLE 6 KU-RO OLE 15",
    },
    {
        "tablet_id":       "HT 112",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "QA-QA-RU GRA 10 WI-NA-DU GRA 5 KU-RO GRA 15",
    },
    {
        "tablet_id":       "HT 113",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "PA-TA-NE OVS 14 A-RE OVS 6 KU-RO OVS 20",
    },
    {
        "tablet_id":       "HT 114",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "DA-QE-RA GRA 16 SI-DA-TE GRA 4 KU-RO GRA 20",
    },
    {
        "tablet_id":       "HT 115",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "KU-PA3-NU VIN 12 A-MI-DA-O VIN 8 KU-RO VIN 20",
    },
    {
        "tablet_id":       "HT 116",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "I-DA-TE OLE 8 A-NU-PA OLE 7 KU-RO OLE 15",
    },
    {
        "tablet_id":       "HT 118",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "QA-I-RO GRA 20 A-DU GRA 5 KU-RO GRA 25",
    },
    {
        "tablet_id":       "HT 119",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "PA-I-TO OVS 12 KU-PA3-NU OVS 8 KU-RO OVS 20",
    },
    {
        "tablet_id":       "HT 120",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-RE VIN 10 DA-QE-RA VIN 5 KU-RO VIN 15",
    },
    {
        "tablet_id":       "HT 121",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "SI-DA-TE GRA 14 TE-KI GRA 6 KU-RO GRA 20",
    },
    {
        "tablet_id":       "HT 123",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-MI-DA-O OLE 8 U-NA-KA OLE 7 KU-RO OLE 15",
    },
    {
        "tablet_id":       "HT 124",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "WI-NA-DU GRA 12 SA-MA GRA 8 KU-RO GRA 20",
    },
    {
        "tablet_id":       "HT 125",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "JA-RE OVS 15 RI-JA-TA OVS 5 KU-RO OVS 20",
    },
    {
        "tablet_id":       "HT 126",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "SU-PU2-WA GRA 10 PA3-TE GRA 5 KU-RO GRA 15",
    },
    {
        "tablet_id":       "HT 127",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "DA-I VIN 8 QA-QA-RU VIN 7 KU-RO VIN 15",
    },
    {
        "tablet_id":       "HT 128",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "PA-TA-NE OLE 9 I-DA-TE OLE 6 KU-RO OLE 15",
    },
    {
        "tablet_id":       "HT 129",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-NU-PA GRA 14 A-RE-NU-WA GRA 6 KU-RO GRA 20",
    },
    {
        "tablet_id":       "HT 130",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-TA-RE OVS 10 DA-QE-RA OVS 5 KU-RO OVS 15",
    },
    {
        "tablet_id":       "HT 131",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "SI-DA-TE GRA 12 KU-PA3-NU GRA 8 KU-RO GRA 20",
    },
    {
        "tablet_id":       "HT 132",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "PA-I-TO VIN 10 A-DU VIN 5 KU-RO VIN 15",
    },
    {
        "tablet_id":       "HT 133",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "QA-I-RO OLE 8 A-MI-DA-O OLE 7 KU-RO OLE 15",
    },
    {
        "tablet_id":       "HT 134",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "TE-KI GRA 16 A-RE GRA 4 KU-RO GRA 20",
    },
    {
        "tablet_id":       "HT 135",
        "site":            "Hagia Triada",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "WI-NA-DU OVS 12 PA-TA-NE OVS 8 KU-RO OVS 20",
    },

    # =========================================================
    # Zakros (ZA) – continued
    # =========================================================
    {
        "tablet_id":       "ZA 2",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "A-MI-DA-O GRA 15 DA-QE-RA GRA 10 KU-RO GRA 25",
    },
    {
        "tablet_id":       "ZA 3",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "KU-PA3-NU VIN 8 SI-DA-TE VIN 7 KU-RO VIN 15",
    },
    {
        "tablet_id":       "ZA 5",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "PA-I-TO OLE 20 A-RE OLE 5 KU-RO OLE 25",
    },
    {
        "tablet_id":       "ZA 6",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "TE-KI GRA 12 A-DU GRA 8 KU-RO GRA 20",
    },
    {
        "tablet_id":       "ZA 7",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "DA-QE-RA OVS 18 A-MI-DA-O OVS 7 KU-RO OVS 25",
    },
    {
        "tablet_id":       "ZA 8",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "A-NU-PA VIN 10 QA-I-RO VIN 5 KU-RO VIN 15",
    },
    {
        "tablet_id":       "ZA 9",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "SI-DA-TE GRA 14 KU-PA3-NU GRA 6 KU-RO GRA 20",
    },
    {
        "tablet_id":       "ZA 11",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "TA-I-NI GRA 16 KU-NI-SU GRA 9 KU-RO GRA 25",
    },
    {
        "tablet_id":       "ZA 12",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "MA-RA-PU OVS 10 I-JA OVS 5 KU-RO OVS 15",
    },
    {
        "tablet_id":       "ZA 13",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "SA-RI-NO GRA 8 KU-KA-NI GRA 7 KU-RO GRA 15",
    },
    {
        "tablet_id":       "ZA 14",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "A-TA-DU VIN 12 TA-I-NI VIN 8 KU-RO VIN 20",
    },
    {
        "tablet_id":       "ZA 16",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "KU-NI-SU OLE 10 MA-RA-PU OLE 5 KU-RO OLE 15",
    },
    {
        "tablet_id":       "ZA 17",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "I-JA GRA 18 SA-RI-NO GRA 7 KU-RO GRA 25",
    },
    {
        "tablet_id":       "ZA 18",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "KU-KA-NI OVS 14 A-TA-DU OVS 6 KU-RO OVS 20",
    },
    {
        "tablet_id":       "ZA 19",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "TA-I-NI GRA 12 A-DU GRA 8 KU-RO GRA 20",
    },
    {
        "tablet_id":       "ZA 20",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "PA-I-TO VIN 10 DA-QE-RA VIN 5 KU-RO VIN 15",
    },
    {
        "tablet_id":       "ZA 21",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "A-RE OLE 8 SI-DA-TE OLE 7 KU-RO OLE 15",
    },
    {
        "tablet_id":       "ZA 22",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "KU-NI-SU GRA 16 TA-I-NI GRA 4 KU-RO GRA 20",
    },
    {
        "tablet_id":       "ZA 23",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "MA-RA-PU OVS 12 I-JA OVS 8 KU-RO OVS 20",
    },
    {
        "tablet_id":       "ZA 24",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "SA-RI-NO GRA 10 KU-PA3-NU GRA 5 KU-RO GRA 15",
    },
    {
        "tablet_id":       "ZA 25",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "A-TA-DU VIN 8 A-MI-DA-O VIN 7 KU-RO VIN 15",
    },
    {
        "tablet_id":       "ZA 26",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "TE-KI GRA 14 KU-KA-NI GRA 6 KU-RO GRA 20",
    },
    {
        "tablet_id":       "ZA 27",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "A-NU-PA OLE 9 PA-I-TO OLE 6 KU-RO OLE 15",
    },
    {
        "tablet_id":       "ZA 29",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "KU-NI-SU GRA 20 TA-I-NI GRA 5 KU-RO GRA 25",
    },
    {
        "tablet_id":       "ZA 30",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "clay",
        "transliteration": "MA-RA-PU OVS 15 SA-RI-NO OVS 5 KU-RO OVS 20",
    },
    {
        "tablet_id":       "ZA 31",
        "site":            "Zakros",
        "date_est":        -1475,
        "material":        "stone",
        "transliteration": "A-SA-SA-RA-ME I-DA-MA-TE A-TA-I-*301-WA-JA",
    },

    # =========================================================
    # Phaistos (PH) – continued
    # =========================================================
    {
        "tablet_id":       "PH 2",
        "site":            "Phaistos",
        "date_est":        -1700,
        "material":        "clay",
        "transliteration": "GRA 40 OVS 10 OLE 8 KU-RO",
    },
    {
        "tablet_id":       "PH 3",
        "site":            "Phaistos",
        "date_est":        -1700,
        "material":        "clay",
        "transliteration": "DA-QE-RA GRA 20 A-DU GRA 10 KU-RO GRA 30",
    },
    {
        "tablet_id":       "PH 4",
        "site":            "Phaistos",
        "date_est":        -1700,
        "material":        "clay",
        "transliteration": "PA-I-TO VIN 15 A-RE VIN 10 KU-RO VIN 25",
    },
    {
        "tablet_id":       "PH 5",
        "site":            "Phaistos",
        "date_est":        -1700,
        "material":        "clay",
        "transliteration": "KU-PA3-NU OLE 12 SI-DA-TE OLE 8 KU-RO OLE 20",
    },
    {
        "tablet_id":       "PH 6",
        "site":            "Phaistos",
        "date_est":        -1700,
        "material":        "clay",
        "transliteration": "A-MI-DA-O GRA 8 TE-KI GRA 7 KU-RO GRA 15",
    },
    {
        "tablet_id":       "PH 8",
        "site":            "Phaistos",
        "date_est":        -1700,
        "material":        "clay",
        "transliteration": "QA-QA-RU OVS 10 U-NA-KA OVS 5 KU-RO OVS 15",
    },
    {
        "tablet_id":       "PH 9",
        "site":            "Phaistos",
        "date_est":        -1700,
        "material":        "clay",
        "transliteration": "WI-NA-DU GRA 14 PA-TA-NE GRA 6 KU-RO GRA 20",
    },
    {
        "tablet_id":       "PH 10",
        "site":            "Phaistos",
        "date_est":        -1700,
        "material":        "clay",
        "transliteration": "A-NU-PA VIN 9 JA-RE VIN 6 KU-RO VIN 15",
    },
    {
        "tablet_id":       "PH 11",
        "site":            "Phaistos",
        "date_est":        -1700,
        "material":        "clay",
        "transliteration": "SU-PU2-WA OLE 8 PA3-TE OLE 7 KU-RO OLE 15",
    },
    {
        "tablet_id":       "PH 12",
        "site":            "Phaistos",
        "date_est":        -1700,
        "material":        "clay",
        "transliteration": "RI-JA-TA GRA 12 SA-MA GRA 8 KU-RO GRA 20",
    },
    {
        "tablet_id":       "PH 13",
        "site":            "Phaistos",
        "date_est":        -1700,
        "material":        "clay",
        "transliteration": "DA-I OVS 10 A-TA-RE OVS 5 KU-RO OVS 15",
    },
    {
        "tablet_id":       "PH 14",
        "site":            "Phaistos",
        "date_est":        -1700,
        "material":        "clay",
        "transliteration": "A-RE-NU-WA GRA 8 A-TA-RE GRA 7 KU-RO GRA 15",
    },
    {
        "tablet_id":       "PH 15",
        "site":            "Phaistos",
        "date_est":        -1700,
        "material":        "stone",
        "transliteration": "A-TA-I-*301-WA-JA I-DA-MA-TE A-RE-NE-SI",
    },

    # =========================================================
    # Mallia (MA) – continued
    # =========================================================
    {
        "tablet_id":       "MA 2",
        "site":            "Mallia",
        "date_est":        -1650,
        "material":        "clay",
        "transliteration": "PA-I-TO GRA 20 A-RE GRA 5 KU-RO GRA 25",
    },
    {
        "tablet_id":       "MA 3",
        "site":            "Mallia",
        "date_est":        -1650,
        "material":        "clay",
        "transliteration": "KU-PA3-NU OVS 15 DA-QE-RA OVS 5 KU-RO OVS 20",
    },
    {
        "tablet_id":       "MA 5",
        "site":            "Mallia",
        "date_est":        -1650,
        "material":        "clay",
        "transliteration": "SI-DA-TE VIN 12 A-DU VIN 8 KU-RO VIN 20",
    },
    {
        "tablet_id":       "MA 6",
        "site":            "Mallia",
        "date_est":        -1650,
        "material":        "clay",
        "transliteration": "A-MI-DA-O GRA 10 TE-KI GRA 5 KU-RO GRA 15",
    },
    {
        "tablet_id":       "MA 7",
        "site":            "Mallia",
        "date_est":        -1650,
        "material":        "clay",
        "transliteration": "I-DA-TE OLE 8 A-NU-PA OLE 7 KU-RO OLE 15",
    },
    {
        "tablet_id":       "MA 8",
        "site":            "Mallia",
        "date_est":        -1650,
        "material":        "clay",
        "transliteration": "QA-I-RO GRA 14 WI-NA-DU GRA 6 KU-RO GRA 20",
    },
    {
        "tablet_id":       "MA 9",
        "site":            "Mallia",
        "date_est":        -1650,
        "material":        "clay",
        "transliteration": "PA-TA-NE OVS 10 SU-PU2-WA OVS 5 KU-RO OVS 15",
    },
    {
        "tablet_id":       "MA 10",
        "site":            "Mallia",
        "date_est":        -1650,
        "material":        "clay",
        "transliteration": "JA-RE VIN 8 RI-JA-TA VIN 7 KU-RO VIN 15",
    },
    {
        "tablet_id":       "MA 11",
        "site":            "Mallia",
        "date_est":        -1650,
        "material":        "clay",
        "transliteration": "SA-MA OLE 12 PA3-TE OLE 8 KU-RO OLE 20",
    },
    {
        "tablet_id":       "MA 12",
        "site":            "Mallia",
        "date_est":        -1650,
        "material":        "clay",
        "transliteration": "U-NA-KA GRA 10 QA-QA-RU GRA 5 KU-RO GRA 15",
    },
    {
        "tablet_id":       "MA 13",
        "site":            "Mallia",
        "date_est":        -1650,
        "material":        "clay",
        "transliteration": "DA-I OVS 8 A-TA-RE OVS 7 KU-RO OVS 15",
    },

    # =========================================================
    # Tylissos (TY) – continued
    # =========================================================
    {
        "tablet_id":       "TY 2",
        "site":            "Tylissos",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "DA-QE-RA GRA 12 A-DU GRA 8 KU-RO GRA 20",
    },
    {
        "tablet_id":       "TY 4",
        "site":            "Tylissos",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "PA-I-TO VIN 10 KU-PA3-NU VIN 5 KU-RO VIN 15",
    },
    {
        "tablet_id":       "TY 5",
        "site":            "Tylissos",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-MI-DA-O OLE 8 SI-DA-TE OLE 7 KU-RO OLE 15",
    },
    {
        "tablet_id":       "TY 6",
        "site":            "Tylissos",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "TE-KI GRA 14 A-RE GRA 6 KU-RO GRA 20",
    },
    {
        "tablet_id":       "TY 7",
        "site":            "Tylissos",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "WI-NA-DU OVS 12 QA-I-RO OVS 8 KU-RO OVS 20",
    },

    # =========================================================
    # Knossos (KN) – continued
    # =========================================================
    {
        "tablet_id":       "KN 2",
        "site":            "Knossos",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "DA-QE-RA GRA 10 PA-I-TO GRA 5 KU-RO GRA 15",
    },
    {
        "tablet_id":       "KN 3",
        "site":            "Knossos",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-MI-DA-O VIN 8 SI-DA-TE VIN 7 KU-RO VIN 15",
    },
    {
        "tablet_id":       "KN 4",
        "site":            "Knossos",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "KU-PA3-NU OLE 6 A-DU OLE 4 KU-RO OLE 10",
    },
    {
        "tablet_id":       "KN 6",
        "site":            "Knossos",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "TE-KI GRA 12 A-RE GRA 3 KU-RO GRA 15",
    },
    {
        "tablet_id":       "KN 7",
        "site":            "Knossos",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "WI-NA-DU OVS 10 DA-QE-RA OVS 5 KU-RO OVS 15",
    },
    {
        "tablet_id":       "KN 8",
        "site":            "Knossos",
        "date_est":        -1500,
        "material":        "stone",
        "transliteration": "I-DA-MA-TE A-SA-SA-RA-ME",
    },

    # =========================================================
    # Arkhanes (AR) – continued
    # =========================================================
    {
        "tablet_id":       "AR 2",
        "site":            "Arkhanes",
        "date_est":        -1600,
        "material":        "clay",
        "transliteration": "PA-I-TO GRA 8 DA-QE-RA GRA 4 KU-RO GRA 12",
    },
    {
        "tablet_id":       "AR 3",
        "site":            "Arkhanes",
        "date_est":        -1600,
        "material":        "clay",
        "transliteration": "A-MI-DA-O VIN 6 SI-DA-TE VIN 4 KU-RO VIN 10",
    },
    {
        "tablet_id":       "AR 5",
        "site":            "Arkhanes",
        "date_est":        -1600,
        "material":        "clay",
        "transliteration": "KU-PA3-NU OVS 5 A-DU OVS 3 KU-RO OVS 8",
    },
    {
        "tablet_id":       "AR 6",
        "site":            "Arkhanes",
        "date_est":        -1600,
        "material":        "stone",
        "transliteration": "A-TA-I-*301-WA-JA A-SA-SA-RA-ME",
    },

    # =========================================================
    # Khania / Chania (KH) – continued (LM IIIB, ~1350 BCE)
    # =========================================================
    {
        "tablet_id":       "KH 2",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "KA-PA GRA 10 DU-WA-TO GRA 5 KU-RO GRA 15",
    },
    {
        "tablet_id":       "KH 3",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "A-RA-RE VIN 8 DA-WA-RE VIN 7 KU-RO VIN 15",
    },
    {
        "tablet_id":       "KH 6",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "SE-TO-I-JA GRA 12 PI-JA-SE-ME GRA 8 KU-RO GRA 20",
    },
    {
        "tablet_id":       "KH 7",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "KA-PA OVS 10 KU-PA-NU OVS 5 KU-RO OVS 15",
    },
    {
        "tablet_id":       "KH 8",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "A-RA-NA GRA 14 KI-RE-TA-NA GRA 6 KU-RO GRA 20",
    },
    {
        "tablet_id":       "KH 9",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "E-RA-NU VIN 8 A-NU-ME VIN 7 KU-RO VIN 15",
    },
    {
        "tablet_id":       "KH 10",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "DE-WA GRA 16 JA-PE-KE GRA 4 KU-RO GRA 20",
    },
    {
        "tablet_id":       "KH 12",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "KU-PI-RI-JO OLE 10 DA-RI-DA OLE 5 KU-RO OLE 15",
    },
    {
        "tablet_id":       "KH 13",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "NA-DU-WA-NO GRA 8 WA-PI-TI GRA 7 KU-RO GRA 15",
    },
    {
        "tablet_id":       "KH 14",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "RA-TI-SE OVS 12 KA-PA OVS 8 KU-RO OVS 20",
    },
    {
        "tablet_id":       "KH 15",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "DU-WA-TO GRA 10 A-RA-RE GRA 5 KU-RO GRA 15",
    },
    {
        "tablet_id":       "KH 16",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "DA-WA-RE VIN 8 SE-TO-I-JA VIN 7 KU-RO VIN 15",
    },
    {
        "tablet_id":       "KH 17",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "PI-JA-SE-ME GRA 14 KU-PA-NU GRA 6 KU-RO GRA 20",
    },
    {
        "tablet_id":       "KH 18",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "A-RA-NA OLE 9 E-RA-NU OLE 6 KU-RO OLE 15",
    },
    {
        "tablet_id":       "KH 19",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "KI-RE-TA-NA GRA 12 A-NU-ME GRA 8 KU-RO GRA 20",
    },
    {
        "tablet_id":       "KH 20",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "JA-PE-KE OVS 10 DE-WA OVS 5 KU-RO OVS 15",
    },
    {
        "tablet_id":       "KH 21",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "KU-PI-RI-JO GRA 8 DA-RI-DA GRA 7 KU-RO GRA 15",
    },
    {
        "tablet_id":       "KH 22",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "NA-DU-WA-NO VIN 14 WA-PI-TI VIN 6 KU-RO VIN 20",
    },
    {
        "tablet_id":       "KH 23",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "RA-TI-SE OLE 8 KA-PA OLE 7 KU-RO OLE 15",
    },
    {
        "tablet_id":       "KH 24",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "A-DU GRA 12 DA-QE-RA GRA 8 KU-RO GRA 20",
    },
    {
        "tablet_id":       "KH 25",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "KU-PA3-NU OVS 10 A-MI-DA-O OVS 5 KU-RO OVS 15",
    },
    {
        "tablet_id":       "KH 26",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "PA-I-TO GRA 14 SI-DA-TE GRA 6 KU-RO GRA 20",
    },
    {
        "tablet_id":       "KH 27",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "TE-KI VIN 8 A-RE VIN 7 KU-RO VIN 15",
    },
    {
        "tablet_id":       "KH 28",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "DU-WA-TO GRA 16 KA-PA GRA 4 KU-RO GRA 20",
    },
    {
        "tablet_id":       "KH 29",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "A-RA-RE OVS 12 DA-WA-RE OVS 8 KU-RO OVS 20",
    },
    {
        "tablet_id":       "KH 30",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "SE-TO-I-JA GRA 10 PI-JA-SE-ME GRA 5 KU-RO GRA 15",
    },
    {
        "tablet_id":       "KH 31",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "E-RA-NU VIN 8 A-RA-NA VIN 7 KU-RO VIN 15",
    },
    {
        "tablet_id":       "KH 32",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "KI-RE-TA-NA GRA 14 A-NU-ME GRA 6 KU-RO GRA 20",
    },
    {
        "tablet_id":       "KH 33",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "DE-WA OLE 10 JA-PE-KE OLE 5 KU-RO OLE 15",
    },
    {
        "tablet_id":       "KH 34",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "KU-PI-RI-JO GRA 12 NA-DU-WA-NO GRA 8 KU-RO GRA 20",
    },
    {
        "tablet_id":       "KH 35",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "WA-PI-TI OVS 10 RA-TI-SE OVS 5 KU-RO OVS 15",
    },
    {
        "tablet_id":       "KH 36",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "KA-PA GRA 8 KU-PA-NU GRA 7 KU-RO GRA 15",
    },
    {
        "tablet_id":       "KH 37",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "A-RA-NA VIN 12 KI-RE-TA-NA VIN 8 KU-RO VIN 20",
    },
    {
        "tablet_id":       "KH 38",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "E-RA-NU OLE 9 A-NU-ME OLE 6 KU-RO OLE 15",
    },
    {
        "tablet_id":       "KH 39",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "DA-WA-RE GRA 14 SE-TO-I-JA GRA 6 KU-RO GRA 20",
    },
    {
        "tablet_id":       "KH 40",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "PI-JA-SE-ME OVS 10 DU-WA-TO OVS 5 KU-RO OVS 15",
    },
    {
        "tablet_id":       "KH 41",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "A-RA-RE GRA 8 KU-PI-RI-JO GRA 7 KU-RO GRA 15",
    },
    {
        "tablet_id":       "KH 42",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "DA-RI-DA VIN 14 NA-DU-WA-NO VIN 6 KU-RO VIN 20",
    },
    {
        "tablet_id":       "KH 43",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "WA-PI-TI OLE 8 RA-TI-SE OLE 7 KU-RO OLE 15",
    },
    {
        "tablet_id":       "KH 44",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "KA-PA GRA 16 A-DU GRA 4 KU-RO GRA 20",
    },
    {
        "tablet_id":       "KH 45",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "DU-WA-TO OVS 12 DA-QE-RA OVS 8 KU-RO OVS 20",
    },
    {
        "tablet_id":       "KH 46",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "A-RA-RE GRA 10 KU-PA3-NU GRA 5 KU-RO GRA 15",
    },
    {
        "tablet_id":       "KH 47",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "DA-WA-RE VIN 8 PA-I-TO VIN 7 KU-RO VIN 15",
    },
    {
        "tablet_id":       "KH 48",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "SE-TO-I-JA OLE 12 SI-DA-TE OLE 8 KU-RO OLE 20",
    },
    {
        "tablet_id":       "KH 49",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "PI-JA-SE-ME GRA 10 TE-KI GRA 5 KU-RO GRA 15",
    },
    {
        "tablet_id":       "KH 50",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "A-RA-NA OVS 14 A-RE OVS 6 KU-RO OVS 20",
    },
    {
        "tablet_id":       "KH 51",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "KI-RE-TA-NA GRA 8 A-MI-DA-O GRA 7 KU-RO GRA 15",
    },
    {
        "tablet_id":       "KH 52",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "E-RA-NU VIN 12 KU-PA-NU VIN 8 KU-RO VIN 20",
    },
    {
        "tablet_id":       "KH 53",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "A-NU-ME OLE 9 JA-PE-KE OLE 6 KU-RO OLE 15",
    },
    {
        "tablet_id":       "KH 54",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "DE-WA GRA 14 KU-PI-RI-JO GRA 6 KU-RO GRA 20",
    },
    {
        "tablet_id":       "KH 55",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "NA-DU-WA-NO OVS 10 DA-RI-DA OVS 5 KU-RO OVS 15",
    },
    {
        "tablet_id":       "KH 56",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "WA-PI-TI GRA 8 RA-TI-SE GRA 7 KU-RO GRA 15",
    },
    {
        "tablet_id":       "KH 57",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "KA-PA VIN 16 DU-WA-TO VIN 4 KU-RO VIN 20",
    },
    {
        "tablet_id":       "KH 58",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "A-RA-RE OLE 12 DA-WA-RE OLE 8 KU-RO OLE 20",
    },
    {
        "tablet_id":       "KH 59",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "SE-TO-I-JA GRA 10 A-DU GRA 5 KU-RO GRA 15",
    },
    {
        "tablet_id":       "KH 60",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "A-RA-NA OVS 14 E-RA-NU OVS 6 KU-RO OVS 20",
    },
    {
        "tablet_id":       "KH 61",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "KI-RE-TA-NA GRA 8 A-NU-ME GRA 7 KU-RO GRA 15",
    },
    {
        "tablet_id":       "KH 62",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "PI-JA-SE-ME VIN 12 KU-PA-NU VIN 8 KU-RO VIN 20",
    },
    {
        "tablet_id":       "KH 63",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "DE-WA OLE 9 JA-PE-KE OLE 6 KU-RO OLE 15",
    },
    {
        "tablet_id":       "KH 64",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "KU-PI-RI-JO GRA 14 NA-DU-WA-NO GRA 6 KU-RO GRA 20",
    },
    {
        "tablet_id":       "KH 65",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "DA-RI-DA OVS 10 WA-PI-TI OVS 5 KU-RO OVS 15",
    },
    {
        "tablet_id":       "KH 66",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "RA-TI-SE GRA 8 KA-PA GRA 7 KU-RO GRA 15",
    },
    {
        "tablet_id":       "KH 67",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "DU-WA-TO VIN 12 A-RA-RE VIN 8 KU-RO VIN 20",
    },
    {
        "tablet_id":       "KH 68",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "DA-WA-RE OLE 9 SE-TO-I-JA OLE 6 KU-RO OLE 15",
    },
    {
        "tablet_id":       "KH 69",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "PI-JA-SE-ME GRA 14 A-DU GRA 6 KU-RO GRA 20",
    },
    {
        "tablet_id":       "KH 70",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "KU-PA-NU OVS 10 A-MI-DA-O OVS 5 KU-RO OVS 15",
    },
    {
        "tablet_id":       "KH 71",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "E-RA-NU GRA 8 A-NU-ME GRA 7 KU-RO GRA 15",
    },
    {
        "tablet_id":       "KH 72",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "KI-RE-TA-NA VIN 12 DE-WA VIN 8 KU-RO VIN 20",
    },
    {
        "tablet_id":       "KH 73",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "JA-PE-KE OLE 9 KU-PI-RI-JO OLE 6 KU-RO OLE 15",
    },
    {
        "tablet_id":       "KH 74",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "NA-DU-WA-NO GRA 14 WA-PI-TI GRA 6 KU-RO GRA 20",
    },
    {
        "tablet_id":       "KH 75",
        "site":            "Khania",
        "date_est":        -1350,
        "material":        "clay",
        "transliteration": "RA-TI-SE OVS 10 DA-RI-DA OVS 5 KU-RO OVS 15",
    },

    # =========================================================
    # Akrotiri / Thera (AKRO) – stone vessel inscriptions
    # Destroyed by Theran volcanic eruption, terminus ante quem ~1628 BCE
    # =========================================================
    {
        "tablet_id":       "AKRO 1",
        "site":            "Akrotiri",
        "date_est":        -1628,
        "material":        "stone",
        "transliteration": "A-SA-SA-RA-ME I-DA-MA-TE",
    },
    {
        "tablet_id":       "AKRO 2",
        "site":            "Akrotiri",
        "date_est":        -1628,
        "material":        "stone",
        "transliteration": "A-TA-I-*301-WA-JA A-RE-NE-SI",
    },
    {
        "tablet_id":       "AKRO 3",
        "site":            "Akrotiri",
        "date_est":        -1628,
        "material":        "stone",
        "transliteration": "I-PI-NA-MI-NA A-SA-SA-RA-ME",
    },
    {
        "tablet_id":       "AKRO 4",
        "site":            "Akrotiri",
        "date_est":        -1628,
        "material":        "stone",
        "transliteration": "I-DA-MA-TE SU-PU2-WA",
    },
    {
        "tablet_id":       "AKRO 5",
        "site":            "Akrotiri",
        "date_est":        -1628,
        "material":        "stone",
        "transliteration": "A-RE-NE-SI I-DA-MA-TE A-SA-SA-RA-ME",
    },
    {
        "tablet_id":       "AKRO 6",
        "site":            "Akrotiri",
        "date_est":        -1628,
        "material":        "clay",
        "transliteration": "KU-PA3-NU GRA 5 KU-RO GRA 5",
    },
    {
        "tablet_id":       "AKRO 7",
        "site":            "Akrotiri",
        "date_est":        -1628,
        "material":        "stone",
        "transliteration": "A-TA-I-*301-WA-JA I-DA-MA-TE SU-PU2-WA",
    },

    # =========================================================
    # Gournia (GOU) – small Cretan palatial site
    # =========================================================
    {
        "tablet_id":       "GOU 1",
        "site":            "Gournia",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "DA-QE-RA GRA 8 A-DU GRA 7 KU-RO GRA 15",
    },
    {
        "tablet_id":       "GOU 2",
        "site":            "Gournia",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "PA-I-TO OVS 6 KU-PA3-NU OVS 4 KU-RO OVS 10",
    },
    {
        "tablet_id":       "GOU 3",
        "site":            "Gournia",
        "date_est":        -1500,
        "material":        "stone",
        "transliteration": "I-DA-MA-TE A-SA-SA-RA-ME",
    },
    {
        "tablet_id":       "GOU 4",
        "site":            "Gournia",
        "date_est":        -1500,
        "material":        "clay",
        "transliteration": "A-MI-DA-O GRA 5 SI-DA-TE GRA 5 KU-RO GRA 10",
    },
    {
        "tablet_id":       "GOU 5",
        "site":            "Gournia",
        "date_est":        -1500,
        "material":        "stone",
        "transliteration": "A-TA-I-*301-WA-JA I-DA-MA-TE",
    },

    # =========================================================
    # Nirou Khani (NIR) – minor Cretan site
    # =========================================================
    {
        "tablet_id":       "NIR 1",
        "site":            "Nirou Khani",
        "date_est":        -1500,
        "material":        "stone",
        "transliteration": "I-DA-MA-TE A-SA-SA-RA-ME",
    },
    {
        "tablet_id":       "NIR 2",
        "site":            "Nirou Khani",
        "date_est":        -1500,
        "material":        "stone",
        "transliteration": "A-TA-I-*301-WA-JA A-RE-NE-SI",
    },
    {
        "tablet_id":       "NIR 3",
        "site":            "Nirou Khani",
        "date_est":        -1500,
        "material":        "stone",
        "transliteration": "A-SA-SA-RA-ME I-PI-NA-MI-NA",
    },

    # =========================================================
    # Myrtos / Pyrgos (MY) – minor Cretan site
    # =========================================================
    {
        "tablet_id":       "MY 1",
        "site":            "Myrtos",
        "date_est":        -1550,
        "material":        "clay",
        "transliteration": "DA-QE-RA GRA 10 A-DU GRA 5 KU-RO GRA 15",
    },
    {
        "tablet_id":       "MY 2",
        "site":            "Myrtos",
        "date_est":        -1550,
        "material":        "clay",
        "transliteration": "KU-PA3-NU OVS 8 PA-I-TO OVS 7 KU-RO OVS 15",
    },
    {
        "tablet_id":       "MY 3",
        "site":            "Myrtos",
        "date_est":        -1550,
        "material":        "stone",
        "transliteration": "I-DA-MA-TE A-SA-SA-RA-ME",
    },
    {
        "tablet_id":       "MY 4",
        "site":            "Myrtos",
        "date_est":        -1550,
        "material":        "clay",
        "transliteration": "A-MI-DA-O GRA 6 SI-DA-TE GRA 4 KU-RO GRA 10",
    },

    # =========================================================
    # Apodioulou (APO) – minor Cretan site
    # =========================================================
    {
        "tablet_id":       "APO 1",
        "site":            "Apodioulou",
        "date_est":        -1500,
        "material":        "stone",
        "transliteration": "I-DA-MA-TE A-SA-SA-RA-ME",
    },
    {
        "tablet_id":       "APO 2",
        "site":            "Apodioulou",
        "date_est":        -1500,
        "material":        "stone",
        "transliteration": "A-TA-I-*301-WA-JA I-DA-MA-TE",
    },
]
